from fastapi import FastAPI, File, UploadFile, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd
import io
import google.generativeai as genai
import resend
import os
from datetime import datetime
import re
from pydantic import BaseModel

app = FastAPI()

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configure APIs
genai.configure(api_key=os.getenv("GEMINI_API_KEY", ""))
resend.api_key = os.getenv("RESEND_API_KEY", "")

def validate_email(email):
    """Simple email validation"""
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return re.match(pattern, email) is not None

def parse_sales_data(file: UploadFile) -> pd.DataFrame:
    """Parse CSV or Excel file"""
    try:
        content = file.file.read()
        file.file.seek(0)
        
        if file.filename.endswith('.csv'):
            df = pd.read_csv(io.BytesIO(content))
        else:
            df = pd.read_excel(io.BytesIO(content))
        
        if df.empty:
            raise HTTPException(status_code=400, detail="File is empty or invalid")
        
        return df
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Error parsing file: {str(e)}")

def generate_sales_insight(df: pd.DataFrame) -> str:
    """Generate AI-powered sales insight"""
    try:
        # Convert DataFrame to readable format
        sales_data = df.to_string()
        
        # Create prompt for Gemini
        prompt = f"""
        Analyze the following sales data and generate an executive sales summary highlighting:
        - Total revenue
        - Best selling product category  
        - Regional performance
        - Sales trends
        
        Sales Data:
        {sales_data}
        
        Please provide a professional, concise executive summary that would be valuable for business decision-making.
        """
        
        # Use Gemini AI
        model = genai.GenerativeModel('gemini-1.5-flash')
        response = model.generate_content(prompt)
        return response.text
        
    except Exception as e:
        # Fallback if AI fails
        return f"""
AI Sales Insight Summary
========================

Dataset Overview:
- Total records: {len(df)}
- Columns analyzed: {len(df.columns)}

Basic Analysis:
The sales data contains {len(df)} records with various columns.
Key patterns and trends can be identified from the dataset.

Note: This is a basic analysis. For detailed AI-powered insights, please ensure Gemini API is properly configured.
        """

async def send_email_insight(email: str, insight: str) -> None:
    """Send sales insight via email"""
    try:
        html_content = f"""
        <html>
        <body style="font-family: Arial, sans-serif; margin: 20px;">
            <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
                <h2 style="color: #333; text-align: center;">📊 AI Sales Insight Report</h2>
                <p style="color: #666;"><strong>Generated on:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <hr style="border: 1px solid #eee; margin: 20px 0;">
                <div style="background-color: #f8f9fa; padding: 20px; border-radius: 5px;">
                    <h3 style="color: #333; margin-top: 0;">Executive Summary</h3>
                    <div style="white-space: pre-wrap; font-family: monospace; background: #fff; padding: 15px; border-radius: 3px;">{insight}</div>
                </div>
                <hr style="border: 1px solid #eee; margin: 20px 0;">
                <p style="color: #666; font-size: 12px; text-align: center;">
                    <em>This report was generated by AI Sales Insight Automation Tool</em>
                </p>
            </div>
        </body>
        </html>
        """
        
        params = {
            "from": "onboarding@resend.dev",
            "to": [email],
            "subject": "📊 AI Sales Insight Report",
            "html": html_content,
        }
        
        r = resend.Emails.send(params)
        print(f"Email sent successfully to {email}: {r}")
        
    except Exception as e:
        print(f"Error sending email: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error sending email: {str(e)}")

class SalesInsightResponse(BaseModel):
    success: bool
    message: str
    insight_id: str = None

@app.get("/")
async def root():
    """Root endpoint"""
    return {"message": "AI Sales Insight Automation API", "version": "1.0.0"}

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {"status": "healthy", "timestamp": datetime.now().isoformat()}

@app.post("/upload", response_model=SalesInsightResponse)
async def upload_and_process(
    file: UploadFile = File(...),
    email: str = Form(...)
):
    """
    Upload sales data file and receive AI-generated insights via email
    
    - **file**: CSV or Excel file containing sales data
    - **email**: Email address to send insights to
    """
    try:
        # Validate email
        if not validate_email(email):
            raise HTTPException(
                status_code=400,
                detail="Invalid email address format"
            )
        
        # Validate file
        if not file.filename:
            raise HTTPException(
                status_code=400,
                detail="No file uploaded"
            )
        
        # Parse sales data
        print(f"Parsing file: {file.filename}")
        df = parse_sales_data(file)
        
        # Generate AI insight
        print("Generating AI insight...")
        insight = generate_sales_insight(df)
        
        # Send email
        print(f"Sending insight to {email}")
        await send_email_insight(email, insight)
        
        return SalesInsightResponse(
            success=True,
            message="Sales insight generated and sent successfully to your email",
            insight_id=f"insight_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        )
        
    except HTTPException:
        raise
    except Exception as e:
        print(f"Unexpected error: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"An unexpected error occurred: {str(e)}"
        )

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
